version: '3.8'

services:
  productapi:
    build:
      context: ../backend
    container_name: productapi
    ports:
      - "8080:8080"
    environment:
      - app.use-mysql=false
    volumes:
      - ../backend/src/main/resources/data/products.json:/app/src/main/resources/data/products.json  # Montar archivo JSON
    networks:
      - backend_network

  frontend:
    build:
      context: ./
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - productapi
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
